services:
  ### DOWNLOADERS ###
  DMB:
    container_name: DMB
    image: iampuid0/dmb:latest ## Optionally, specify a specific version of DMB w/ image: iampuid0/dmb:2.0.0
    stop_grace_period: 30s ## Adjust as need to allow for graceful shutdown of the container
    shm_size: 128mb ## Increased for PostgreSQL
    stdin_open: true ## docker run -i
    tty: true ## docker run -t
    volumes:
      - ${ROOT}/MediaCenter/config/DMB/config:/config ## Location of configuration files. If a Zurg config.yml and/or Zurg app is placed here, it will be used to override the default configuration and/or app used at startup.
      - ${ROOT}/MediaCenter/config/DMB/log:/log ## Location for logs
      - ${ROOT}/MediaCenter/config/DMB/Zurg/RD:/zurg/RD ## Location for Zurg RealDebrid active configuration
      - ${ROOT}/MediaCenter/config/DMB/Zurg/mnt:/data:shared ## Location for rclone mount to host
      - ${ROOT}/MediaCenter/config/DMB/PostgreSQL/data:/postgres_data ## Location for PostgreSQL database
      - ${ROOT}/MediaCenter/config/DMB/pgAdmin4/data:/pgadmin/data ## Location for pgAdmin 4 data
      - ${ROOT}/MediaCenter/config/DMB/Zilean/data:/zilean/app/data ## Location for Zilean data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ZURG_INSTANCES_REALDEBRID_API_KEY=${RD_API_KEY}
      - DMB_LOG_LEVEL=INFO
    ports:
      - "3005:3005" ## DMB Frontend
      - "5050:5050" ## pgAdmin 4
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - no-new-privileges

  decypharr:
    image: cy01/blackhole:latest # or cy01/blackhole:beta
    container_name: decypharr
    ports:
      - "8000:8282" # qBittorrent
      - "8111:8181" # Proxy
    user: "1000:1000"
    volumes:
      - ${HDDSTORAGE}:/MediaCenterBox
      - ${ROOT}/MediaCenter/config/decypharr:/app # config.json must be in this directory
      - ${ROOT}/MediaCenter/config/DMB/Zurg/mnt:/data
      - ${ROOT}/MediaCenter/config/decypharr/mnt:/MediaCenterBox/RD-DL
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
      - QBIT_PORT=8282 # qBittorrent Port. This is optional. You can set this in the config file
      - PORT=8181 # Proxy Port. This is optional. You can set this in the config file
    restart: unless-stopped
    depends_on:
      DMB:
        condition: service_healthy
        restart: true

  deluge:
    container_name: deluge
    labels:
      - homepage.group=Downloaders
      - homepage.name=Deluge
      - homepage.icon=deluge.png
      - homepage.href=http://${HOSTNAME}:8112
      - homepage.description=Deluge Torrents (Private Trackers)
      - homepage.widget.type=deluge
      - homepage.widget.url=http://${HOSTNAME}:8112
      - homepage.widget.password=deluge
      - homepage.widget.enableLeechProgress=true
    image: linuxserver/deluge:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/MediaCenter/config/deluge:/config
      - ${HDDSTORAGE}:/MediaCenterBox
    network_mode: host

  ### INDEXERS ###
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    labels:
      - homepage.group=Indexers
      - homepage.name=Prowlarr
      - homepage.icon=prowlarr.png
      - homepage.href=http://${HOSTNAME}:9696
      - homepage.description=Prowlarr Indexers
      - homepage.widget.type=prowlarr
      - homepage.widget.url=http://${HOSTNAME}:9696
      - homepage.widget.key=${PROWLARR_API_KEY}
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/MediaCenter/config/prowlarr:/config
    restart: unless-stopped
    ports:
      - 9696:9696

  sonarr:
    container_name: sonarr
    labels:
      - homepage.group=Indexers
      - homepage.name=Sonarr
      - homepage.icon=sonarr.png
      - homepage.href=http://${HOSTNAME}:8989
      - homepage.description=Non-4K Series
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://${HOSTNAME}:8989
      - homepage.widget.key=${SONARR_API_KEY}
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/MediaCenter/config/sonarr:/config
      - ${ROOT}/MediaCenter/config/decypharr/mnt:/MediaCenterBox/RD-DL
      - ${ROOT}/MediaCenter/config/DMB/Zurg/mnt:/data
      - ${HDDSTORAGE}:/MediaCenterBox
    depends_on:
      decypharr:
        condition: service_healthy
        restart: true

  sonarr-4k:
    container_name: sonarr-4k
    labels:
      - homepage.group=Indexers
      - homepage.name=Sonarr 4K
      - homepage.icon=sonarr.png
      - homepage.href=http://${HOSTNAME}:8888
      - homepage.description=4K Series
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://${HOSTNAME}:8888
      - homepage.widget.key=${SONARR_4K_API_KEY}
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - 8888:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/MediaCenter/config/sonarr-4k:/config
      - ${ROOT}/MediaCenter/config/decypharr/mnt:/MediaCenterBox/RD-DL
      - ${ROOT}/MediaCenter/config/DMB/Zurg/mnt:/data
      - ${HDDSTORAGE}:/MediaCenterBox
    depends_on:
      decypharr:
        condition: service_healthy
        restart: true

  radarr:
    container_name: radarr
    labels:
      - homepage.group=Indexers
      - homepage.name=Radarr
      - homepage.icon=radarr.png
      - homepage.href=http://${HOSTNAME}:7878
      - homepage.description=Non-4K Movies
      - homepage.widget.type=radarr
      - homepage.widget.url=http://${HOSTNAME}:7878
      - homepage.widget.key=${RADARR_API_KEY}
    image: linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/MediaCenter/config/radarr:/config
      - ${ROOT}/MediaCenter/config/decypharr/mnt:/MediaCenterBox/RD-DL
      - ${ROOT}/MediaCenter/config/DMB/Zurg/mnt:/data
      - ${HDDSTORAGE}:/MediaCenterBox
    depends_on:
      decypharr:
        condition: service_healthy
        restart: true

  radarr-4k:
    container_name: radarr-4k
    labels:
      - homepage.group=Indexers
      - homepage.name=Radarr 4K
      - homepage.icon=radarr.png
      - homepage.href=http://${HOSTNAME}:7979
      - homepage.description=4K Movies
      - homepage.widget.type=radarr
      - homepage.widget.url=http://${HOSTNAME}:7979
      - homepage.widget.key=${RADARR_4K_API_KEY}
    image: linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - 7979:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/MediaCenter/config/radarr-4k:/config
      - ${ROOT}/MediaCenter/config/decypharr/mnt:/MediaCenterBox/RD-DL
      - ${ROOT}/MediaCenter/config/DMB/Zurg/mnt:/data
      - ${HDDSTORAGE}:/MediaCenterBox
    depends_on:
      decypharr:
        condition: service_healthy
        restart: true

  ### MEDIA SERVER ###
  jellyfin:
    container_name: jellyfin
    labels:
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin.png
      - homepage.href=http://${HOSTNAME}:8096
      - homepage.description=Media server
      - homepage.widget.type=jellyfin
      - homepage.widget.url=http://${HOSTNAME}:8096
      - homepage.widget.key=${JELLYFIN_API_KEY}
    image: lscr.io/linuxserver/jellyfin
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel|ghcr.io/themepark-dev/theme.park:jellyfin
      - TP_COMMUNITY_THEME=true
      - TP_THEME=rose-pine-moon
    network_mode: host
    volumes:
      - ${ROOT}/MediaCenter/config/jellyfin:/config
      - ${ROOT}/MediaCenter/config/jellyfin/transcode:/transcode
      - ${ROOT}/MediaCenter/config/DMB/Zurg/mnt:/data
      - ${HDDSTORAGE}/Completed:/MediaCenterBox
      - ~/IPTVBoss/output:/IPTVBoss
    devices:
      - /dev/dri:/dev/dri
    depends_on:
      DMB:
        condition: service_healthy
        restart: true

  ### HOUSEKEEPING ###
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:amd64-latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - WATCHTOWER_SCHEDULE= 0 0 6 * * * #      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_NOTIFICATIONS_LEVEL=debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 1903:3000
    volumes:
      - ${ROOT}/MediaCenter/config/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOSTNAME}

  ### OTHER ###
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    labels:
      - homepage.group=Requests
      - homepage.name=Jellyseerr
      - homepage.icon=jellyseerr.png
      - homepage.href=http://${HOSTNAME}:5055
      - homepage.description=User media requests
      - homepage.widget.type=jellyseerr
      - homepage.widget.url=http://${HOSTNAME}:5055
      - homepage.widget.key=${JELLYSEERR_API_KEY}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - LOG_LEVEL=debug
    ports:
      - 5055:5055
    volumes:
      - ${ROOT}/MediaCenter/config/jellyseerr:/app/config
    restart: unless-stopped

  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: thelounge
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - ~/.thelounge:/var/opt/thelounge
